### ISSUE TITLE
New workspace directory created at random

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#187] opened 2017-11-13 22:02 UTC
When moving files within a Jupyter Notebook and then viewing folder / file structure within 3Blades, the `workspaces` directory appears.

From the 3Blades UI:

<img width="1104" alt="screen shot 2017-11-13 at 4 57 13 pm" src="https://user-images.githubusercontent.com/920170/32751566-6497e7b2-c894-11e7-8307-7514ce47fe35.png">

From the Notebook UI:

<img width="1147" alt="screen shot 2017-11-13 at 5 01 16 pm" src="https://user-images.githubusercontent.com/920170/32751611-8c211c7c-c894-11e7-93b7-89b1ff3e1f17.png">

**Comment by johngriebel** [comment] 2017-11-14 11:29
@jgwerner I'm working on reproducing this - no luck so far. As an aside, do we want to include the `.ipynb_checkpoints` directory? It's not something the user explicitly created on their own, but it may be useful to include it as the current behavior does.

**Comment by johngriebel** [comment] 2017-11-14 12:29
@jgwerner this seems to be a race condition. I have the cause figured out (I think), I just need to come up with a solution.

**Comment by johngriebel** [comment] 2017-11-30 11:33
@jgwerner closing this since we haven't seen it happen again.

**Closed by johngriebel** 2017-11-30 11:33 UTC
Labels: type/fix
