### ISSUE TITLE
Port CLI tools to Node.js

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#110] opened 2017-07-27 15:59 UTC
- [ ] Prototype
- [ ] Alpha
- [ ] Beta
- [ ] Release Candidate
- [ ] Live

> Moving from Alpha to Beta to RC should happen fast.

**Comment by johngriebel** [comment] 2017-09-06 11:13
Closing this as a duplicate of #111.

**Closed by johngriebel** 2017-09-06 11:13 UTC
Labels: duplicate, type/epic, type/feature
