### ISSUE TITLE
Creating a server name with dash does not work

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#126] opened 2017-09-08 02:02 UTC
Creating a server name with dash (-) or dashes does not allow users to start the server.

To replicate, create a new server resource with a dash or dashes, such as `my-server-nb`. Then click on Start.

In this case you will notice that unlike other server types the server does not change state from `Stopped` to `Running`.

cc/ @johngriebel @jkp85

**Comment by johngriebel** [comment] 2017-09-08 02:24
@jgwerner I'm not surprised this happens, in the backend we call `slugify` on the server name. I bet there is an edge case there. Perhaps we should prevent server names with dashes?

**Comment by jgwerner** [comment] 2017-09-08 02:26
@johngriebel that could work to start, but don't know what the cost is to validate proper syntax with all front end elements vs handling dashes properly the backend.

**Comment by johngriebel** [comment] 2017-09-08 02:27
Right, we'll take a more earnest look tomorrow. Perhaps it's trivial to do the "right" way

**Comment by johngriebel** [comment] 2017-09-27 10:32
I've retested this in dev, and was not able to replicate the issue. I suspect the root cause was something unrelated to the server's name containing dashes. Closing.

**Closed by johngriebel** 2017-09-27 10:32 UTC
Labels: type/fix
