### ISSUE TITLE
Document and version control restful server schema

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#27] opened 2017-02-08 18:40 UTC
Model servers have a standard schema. We should create documentation for this schema and also version control endpoint. Adding as epic since version control and docs could involve several touch points, such as admin console, base server image, doc location, url format, among others.

**Comment by johngriebel** [comment] 2017-07-18 15:18
Closing as duplicate of #13.

**Closed by johngriebel** 2017-07-18 15:18 UTC
Labels: epic, feature, priority 2
