### ISSUE TITLE
Upload files with new file upload endpoint

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#28] opened 2017-02-08 18:45 UTC
Updating issue so that uploads work with new endpoint. When uploading a large file (70Mb in the test) with the browser:

- UI hangs and no additional feedback is available due to the lack of a progress bar.
- The 'Upload' maintains style that it can be clicked again.
- File size should be checked and limited from the browser.

Large files (more than 10 or 15 MBytes) should not be uploaded via browser. Other options should only be used for importing or uploading large files, such as with AWS S3 and CLI Tools, respectively.

**Comment by jkp85** [comment] 2017-05-10 10:36
Related to 3Blades/cli-tools#48

**Comment by jgwerner** [comment] 2017-06-20 18:42
Consolidating with #74.

**Comment by johngriebel** [comment] 2017-06-21 12:29
@jgwerner Can we close this as a duplicate of #74 and [cli-tools/#48](https://github.com/3Blades/cli-tools/issues/48)?

**Comment by jgwerner** [comment] 2017-06-21 13:22
We should have validation in the `react-front` repo to reject files larger than XX, and preferably should be a config that can be set before `npm run start`. I'll open a new issue in `react-frontend` for that, reference #74  and close this one.

**Closed** 2017-06-21 13:22 UTC
Labels: epic, feature, onpremise, SaaS
